services:
  postgres:
    image: postgres:17
    container_name: invoker-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: invoker_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: invoker-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093

      # advertise both docker + host
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://invoker-kafka:9092,PLAINTEXT_HOST://localhost:29092

      # protocol mapping (REQUIRED)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@invoker-kafka:9093

      # single broker settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

    volumes:
      - kafka_data:/var/lib/kafka/data


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: invoker-kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=invoker-local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=invoker-kafka:9092
    depends_on:
      - kafka
volumes:
  postgres_data:
  kafka_data:
